version: '3'

services:
  php:
    container_name: app-php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    restart: unless-stopped
    tty: true
    volumes:
      - ./app-crawler:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel
  
  nginx:
    container_name: app-nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
      args:
          - UID=${UID:-1000}
          - GID=${GID:-1000}
    restart: unless-stopped
    tty: true
    ports:
      - '8180:80'
      - '443:443'
    volumes:
      - ./app-crawler:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
  
  mysql:
    container_name: app-mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    volumes:
      - app-data:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - laravel
    ports:
      - '3376:3306'
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"

  redis:
    container_name: app-redis
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    ports:
      - '6381:6379'

  npm:
    container_name: "npm"
    image: node:current-alpine
    volumes:
        - ./src:/var/www/html
    ports:
        - "${FORWARD_NPM_PORT:-3000}:3000"
    working_dir: /var/www/html
    entrypoint: ["npm"]
    networks:
        - laravel

networks:
  laravel:
    driver: bridge

volumes:
  app-data:
    driver: local
